colors_dict = {
    "Mac": "#A52A2A",
    "T": "#FF0000",
    "PT": "#228B22",
    "TAL": "#3CB371",
    "CNT": "#90EE90",
    "MDC": "#8B4513",
    "VSM/P": "#20B2AA",
    "PC": "#DAA520",
    "IC": "#1E90FF",
    "MAST": "#FF1493",
    "EC": "#00BFFF",
    "DTL": "#00FA9A",
    "ATL": "#32CD32",
    "FIB": "#4682B4",
    "DCT": "#98FB98",
    "PEC": "#008080",
    "glom. EC": "#22BFD8",
    "PL": "#6495ED",
    "N": "#800000",
    "B": "#4169E1",
    "POD": "#800080",
    "MC": "#FFD700",
    "cycMNP": "#FFB6C1",
    "pDC": "#DB7093",
    "cDC": "#FF69B4",
    "PapE": "#006400",
    "NEU": "#FFD700",
}

colors_new = {
    "other kidney cell": "#573b00",
    "APC": "#97ff00",
    "CD8+": "#d60000",
    "CD4+": "#8c3bff",
    "other immune": "#00acc6",
    "Tregs": "#ff7ed1",
    "MAIT": "#6b004f",
    "gdT": "#ffa52f",
    "NKT-like": "#005659",
    "glom. cell": "#018700",
}

# provided by robin
colors_dict_old = {
    "podocyte": "#800080",
    "PEC": "#008080",
    "mesangial cell": "#FFD700",
    "EC": "#00BFFF",
    "VSM/P": "#20B2AA",
    "PapE": "#006400",
    "PT": "#228B22",
    "ATL": "#32CD32",
    "CNT": "#90EE90",
    "DCT": "#98FB98",
    "DTL": "#00FA9A",
    "TAL": "#3CB371",
    "FIB": "#4682B4",
    "IC": "#1E90FF",
    "Transformed mesangial": "black",
    "NEU": "#FFD700",
    "PC": "#DAA520",
    "T": "#FF0000",
    "NKC/T": "#DC143C",
    "B": "#4169E1",
    "PL": "#6495ED",
    "N": "#800000",
    "MAC": "#A52A2A",
    "MDC": "#8B4513",
    "Mono": "#D2691E",
    "MAST": "#FF1493",
    "cDC": "#FF69B4",
    "pDC": "#DB7093",
    "cycMNP": "#FFB6C1",
    "cycNKC/T": "#FFC0CB",
}


colors_sub = {
    "CD8+": "#1C3FFD",
    "CD4+": "#FFBE00",
    # "other kidney cell": "#c4d0a7",
    "other kidney cell": "#c5c5c5",
    # "APC": "#927e71",
    "APC": "#72563D",
    "other immune": "#ffaa84",
    "Tregs": "#512DA8",
    "MAIT": "#9C27B0",
    "gdT": "#DB0000",
    "NKT-like": "#0D6986",
    "glom. cell": "#33691E",
}


cell_to_group = {
    # Nephron tubular epithelium
    "IC": "other kidney cell",
    "PC": "other kidney cell",
    "MDC": "other kidney cell",
    "CNT": "other kidney cell",
    "DCT": "other kidney cell",
    "PT": "other kidney cell",
    "DTL": "other kidney cell",
    "ATL": "other kidney cell",
    "TAL": "other kidney cell",
    # Glomerular/parietal epithelium
    "POD": "glom. cell",
    "PEC": "glom. cell",
    # Endothelium & vascular support
    "EC": "other kidney cell",
    "glom. EC": "glom. cell",
    "VSM/P": "other kidney cell",
    # Mesangial & interstitial stroma
    "MC": "other kidney cell",
    "FIB": "other kidney cell",
    # Immune myeloid lineage
    "Mac": "APC",
    "cDC": "APC",
    "cycMNP": "other immune",
    "N": "other immune",
    "MAST": "other immune",
    # Immune lymphoid lineage
    # "CD4+": "Immune lymphoid",
    # "CD8+": "Immune lymphoid",
    # "Tregs": "Immune lymphoid",
    # "gdT": "Immune lymphoid",
    # "MAIT": "Immune lymphoid",
    # "NKT-like": "Immune lymphoid",
    "B": "APC",
    "PL": "other immune",
    # Unclassified
    "unknown": "other kidney cell",
    "NEU": "other kidney cell",
}
